'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="school_mgm_db")>  _
Partial Public Class bindSourceDBDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InserttblStudentInfo(instance As tblStudentInfo)
    End Sub
  Partial Private Sub UpdatetblStudentInfo(instance As tblStudentInfo)
    End Sub
  Partial Private Sub DeletetblStudentInfo(instance As tblStudentInfo)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.School_Management_System.My.MySettings.Default.school_mgm_dbConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tblStudentInfos() As System.Data.Linq.Table(Of tblStudentInfo)
		Get
			Return Me.GetTable(Of tblStudentInfo)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblStudentInfo")>  _
Partial Public Class tblStudentInfo
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _studentID As String
	
	Private _pictureID As System.Data.Linq.Binary
	
	Private _lastname As String
	
	Private _firstname As String
	
	Private _MI As String
	
	Private _address As String
	
	Private _gender As String
	
	Private _birthDate As System.Nullable(Of Date)
	
	Private _birthPlace As String
	
	Private _maidenName As String
	
	Private _maidenCN As String
	
	Private _fatherName As String
	
	Private _fatherCN As String
	
	Private _emergencyName As String
	
	Private _emergencyCN As String
	
	Private _status As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnstudentIDChanging(value As String)
    End Sub
    Partial Private Sub OnstudentIDChanged()
    End Sub
    Partial Private Sub OnpictureIDChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnpictureIDChanged()
    End Sub
    Partial Private Sub OnlastnameChanging(value As String)
    End Sub
    Partial Private Sub OnlastnameChanged()
    End Sub
    Partial Private Sub OnfirstnameChanging(value As String)
    End Sub
    Partial Private Sub OnfirstnameChanged()
    End Sub
    Partial Private Sub OnMIChanging(value As String)
    End Sub
    Partial Private Sub OnMIChanged()
    End Sub
    Partial Private Sub OnaddressChanging(value As String)
    End Sub
    Partial Private Sub OnaddressChanged()
    End Sub
    Partial Private Sub OngenderChanging(value As String)
    End Sub
    Partial Private Sub OngenderChanged()
    End Sub
    Partial Private Sub OnbirthDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnbirthDateChanged()
    End Sub
    Partial Private Sub OnbirthPlaceChanging(value As String)
    End Sub
    Partial Private Sub OnbirthPlaceChanged()
    End Sub
    Partial Private Sub OnmaidenNameChanging(value As String)
    End Sub
    Partial Private Sub OnmaidenNameChanged()
    End Sub
    Partial Private Sub OnmaidenCNChanging(value As String)
    End Sub
    Partial Private Sub OnmaidenCNChanged()
    End Sub
    Partial Private Sub OnfatherNameChanging(value As String)
    End Sub
    Partial Private Sub OnfatherNameChanged()
    End Sub
    Partial Private Sub OnfatherCNChanging(value As String)
    End Sub
    Partial Private Sub OnfatherCNChanged()
    End Sub
    Partial Private Sub OnemergencyNameChanging(value As String)
    End Sub
    Partial Private Sub OnemergencyNameChanged()
    End Sub
    Partial Private Sub OnemergencyCNChanging(value As String)
    End Sub
    Partial Private Sub OnemergencyCNChanged()
    End Sub
    Partial Private Sub OnstatusChanging(value As String)
    End Sub
    Partial Private Sub OnstatusChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_studentID", DbType:="VarChar(255) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property studentID() As String
		Get
			Return Me._studentID
		End Get
		Set
			If (String.Equals(Me._studentID, value) = false) Then
				Me.OnstudentIDChanging(value)
				Me.SendPropertyChanging
				Me._studentID = value
				Me.SendPropertyChanged("studentID")
				Me.OnstudentIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pictureID", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property pictureID() As System.Data.Linq.Binary
		Get
			Return Me._pictureID
		End Get
		Set
			If (Object.Equals(Me._pictureID, value) = false) Then
				Me.OnpictureIDChanging(value)
				Me.SendPropertyChanging
				Me._pictureID = value
				Me.SendPropertyChanged("pictureID")
				Me.OnpictureIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lastname", DbType:="VarChar(255)")>  _
	Public Property lastname() As String
		Get
			Return Me._lastname
		End Get
		Set
			If (String.Equals(Me._lastname, value) = false) Then
				Me.OnlastnameChanging(value)
				Me.SendPropertyChanging
				Me._lastname = value
				Me.SendPropertyChanged("lastname")
				Me.OnlastnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_firstname", DbType:="VarChar(255)")>  _
	Public Property firstname() As String
		Get
			Return Me._firstname
		End Get
		Set
			If (String.Equals(Me._firstname, value) = false) Then
				Me.OnfirstnameChanging(value)
				Me.SendPropertyChanging
				Me._firstname = value
				Me.SendPropertyChanged("firstname")
				Me.OnfirstnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MI", DbType:="VarChar(255)")>  _
	Public Property MI() As String
		Get
			Return Me._MI
		End Get
		Set
			If (String.Equals(Me._MI, value) = false) Then
				Me.OnMIChanging(value)
				Me.SendPropertyChanging
				Me._MI = value
				Me.SendPropertyChanged("MI")
				Me.OnMIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_address", DbType:="VarChar(255)")>  _
	Public Property address() As String
		Get
			Return Me._address
		End Get
		Set
			If (String.Equals(Me._address, value) = false) Then
				Me.OnaddressChanging(value)
				Me.SendPropertyChanging
				Me._address = value
				Me.SendPropertyChanged("address")
				Me.OnaddressChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_gender", DbType:="VarChar(255)")>  _
	Public Property gender() As String
		Get
			Return Me._gender
		End Get
		Set
			If (String.Equals(Me._gender, value) = false) Then
				Me.OngenderChanging(value)
				Me.SendPropertyChanging
				Me._gender = value
				Me.SendPropertyChanged("gender")
				Me.OngenderChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_birthDate", DbType:="DateTime2")>  _
	Public Property birthDate() As System.Nullable(Of Date)
		Get
			Return Me._birthDate
		End Get
		Set
			If (Me._birthDate.Equals(value) = false) Then
				Me.OnbirthDateChanging(value)
				Me.SendPropertyChanging
				Me._birthDate = value
				Me.SendPropertyChanged("birthDate")
				Me.OnbirthDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_birthPlace", DbType:="VarChar(255)")>  _
	Public Property birthPlace() As String
		Get
			Return Me._birthPlace
		End Get
		Set
			If (String.Equals(Me._birthPlace, value) = false) Then
				Me.OnbirthPlaceChanging(value)
				Me.SendPropertyChanging
				Me._birthPlace = value
				Me.SendPropertyChanged("birthPlace")
				Me.OnbirthPlaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_maidenName", DbType:="VarChar(255)")>  _
	Public Property maidenName() As String
		Get
			Return Me._maidenName
		End Get
		Set
			If (String.Equals(Me._maidenName, value) = false) Then
				Me.OnmaidenNameChanging(value)
				Me.SendPropertyChanging
				Me._maidenName = value
				Me.SendPropertyChanged("maidenName")
				Me.OnmaidenNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_maidenCN", DbType:="VarChar(255)")>  _
	Public Property maidenCN() As String
		Get
			Return Me._maidenCN
		End Get
		Set
			If (String.Equals(Me._maidenCN, value) = false) Then
				Me.OnmaidenCNChanging(value)
				Me.SendPropertyChanging
				Me._maidenCN = value
				Me.SendPropertyChanged("maidenCN")
				Me.OnmaidenCNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fatherName", DbType:="VarChar(255)")>  _
	Public Property fatherName() As String
		Get
			Return Me._fatherName
		End Get
		Set
			If (String.Equals(Me._fatherName, value) = false) Then
				Me.OnfatherNameChanging(value)
				Me.SendPropertyChanging
				Me._fatherName = value
				Me.SendPropertyChanged("fatherName")
				Me.OnfatherNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fatherCN", DbType:="VarChar(255)")>  _
	Public Property fatherCN() As String
		Get
			Return Me._fatherCN
		End Get
		Set
			If (String.Equals(Me._fatherCN, value) = false) Then
				Me.OnfatherCNChanging(value)
				Me.SendPropertyChanging
				Me._fatherCN = value
				Me.SendPropertyChanged("fatherCN")
				Me.OnfatherCNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_emergencyName", DbType:="VarChar(255)")>  _
	Public Property emergencyName() As String
		Get
			Return Me._emergencyName
		End Get
		Set
			If (String.Equals(Me._emergencyName, value) = false) Then
				Me.OnemergencyNameChanging(value)
				Me.SendPropertyChanging
				Me._emergencyName = value
				Me.SendPropertyChanged("emergencyName")
				Me.OnemergencyNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_emergencyCN", DbType:="VarChar(255)")>  _
	Public Property emergencyCN() As String
		Get
			Return Me._emergencyCN
		End Get
		Set
			If (String.Equals(Me._emergencyCN, value) = false) Then
				Me.OnemergencyCNChanging(value)
				Me.SendPropertyChanging
				Me._emergencyCN = value
				Me.SendPropertyChanged("emergencyCN")
				Me.OnemergencyCNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_status", DbType:="VarChar(255)")>  _
	Public Property status() As String
		Get
			Return Me._status
		End Get
		Set
			If (String.Equals(Me._status, value) = false) Then
				Me.OnstatusChanging(value)
				Me.SendPropertyChanging
				Me._status = value
				Me.SendPropertyChanged("status")
				Me.OnstatusChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
